version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000" # Ensure the app is running on port 5000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev # Use this to start the development server
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/airqualitydb # MongoDB URI for connection

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017" # Ensure MongoDB is accessible on port 27017
    volumes:
      - mongo-data:/data/db # Persist MongoDB data

volumes:
  mongo-data:
